version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing app dependencies...
      - npm install
  build:
    commands:
      - npm run-script build
      - echo Building static site...
artifacts:
  files:
    - build/**/*
    - node_modules/**/*
    - package.json